export const locations = [
  {
    IDENTIFICADOR: "FR07180",
    NOMBRE: "BOSQUE DE CHAPULTEPEC",
    ALCALDÍA: "MIGUEL HIDALGO",
    COLONIA: "Bosque de Chapultepec",
    CALLE: "Paseo de la Reforma I Sección",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 11100,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "27/31",
    "APS SIN CONEXIÓN": 4,
    "GW SIN CONEXIÓN": "GW005/GW006/GW021(GW032",
    LATITUD: "19,419487",
    LONGITUD: "-99,1905595",
    geopoint: "19.419487, -99.1905595",
  },
  {
    IDENTIFICADOR: "FR07179",
    NOMBRE: "BOSQUE DE ARAGÓN",
    ALCALDÍA: "GUSTAVO A. MADERO",
    COLONIA: "Zoológico de San Juan de Aragón",
    CALLE: "Av. José Loreto Fabela",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 15520,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "10/10",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,463244",
    LONGITUD: "-99,063716",
    geopoint: "19.463244, -99.063716",
  },
  {
    IDENTIFICADOR: "FR07178",
    NOMBRE: "VIVEROS DE COYOACÁN",
    ALCALDÍA: "COYOACÁN",
    COLONIA: "Del Carmen",
    CALLE: "Av. Progreso",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 4100,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "5/6",
    "APS SIN CONEXIÓN": 1,
    "GW SIN CONEXIÓN": "GW008",
    LATITUD: "19,353702",
    LONGITUD: "-99,171766",
    geopoint: "19.353702, -99.171766",
  },
  {
    IDENTIFICADOR: "FR07177",
    NOMBRE: "PLAZA GARIBALDI",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Centro",
    CALLE: "Eje Central Lázaro Cárdenas",
    NÚMERO: 43,
    "CÓDIGO POSTAL": 6000,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,4403975",
    LONGITUD: "-99,1392127",
    geopoint: "19.4403975, -99.1392127",
  },
  {
    IDENTIFICADOR: "FR06679",
    NOMBRE: "PLAZA CIVICA SAN PEDRO ATOCPAN",
    ALCALDÍA: "MILPA ALTA",
    COLONIA: "San Pedro Atocpan",
    CALLE: "Venustiano Carranza y Francisco I. Madero",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 12200,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,20126",
    LONGITUD: "-99,049978",
    geopoint: "19.20126, -99.049978",
  },
  {
    IDENTIFICADOR: "FR06395",
    NOMBRE: "PLAZA CIVICA VALENTIN CAMPA",
    ALCALDÍA: "IZTAPALAPA",
    COLONIA: "Ejidos de Santa María Aztahuacan",
    CALLE: "20 de noviembre Esq. con Plan de San Luis",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 9570,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,354656",
    LONGITUD: "-99,032081",
    geopoint: "19.354656, -99.032081",
  },
  {
    IDENTIFICADOR: "FR06394",
    NOMBRE: "PARQUE CULTURAL INFANTIL (PATOLLI SAN MIGUEL TEOTONGO)",
    ALCALDÍA: "IZTAPALAPA",
    COLONIA: "San Miguel Teotongo",
    CALLE: "Jacaranda",
    NÚMERO: 43,
    "CÓDIGO POSTAL": 9630,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,344196",
    LONGITUD: "-98,989499",
    geopoint: "19.344196, -98.989499",
  },
  {
    IDENTIFICADOR: "FR06392",
    NOMBRE: "PARQUE CULTURAL INFANTIL (PATOLLI CANAL NACIONAL)",
    ALCALDÍA: "IZTAPALAPA",
    COLONIA: "José López Portillo",
    CALLE: "Periférico Oriente Canal de Garay esquina Calle 20",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 9208,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,377081",
    LONGITUD: "-99,059794",
    geopoint: "19.377081, -99.059794",
  },
  {
    IDENTIFICADOR: "FR06391",
    NOMBRE: "PARQUE CULTURAL INFANTIL (PATOLLI CABEZA DE JUÁREZ)",
    ALCALDÍA: "IZTAPALAPA",
    COLONIA: "Chinampac de Juárez",
    CALLE: "Camellón de Periférico y Eje 5 Sur",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 9208,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,377414",
    LONGITUD: "-99,060142",
    geopoint: "19.377414, -99.060142",
  },
  {
    IDENTIFICADOR: "FR06322",
    NOMBRE: "PLAZA DE LA CONSTITUCIÓN (EL ZOCALO)",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Centro",
    CALLE: "Plaza de la Constitución",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 6000,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "12/12",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,431275",
    LONGITUD: "-99,132424",
    geopoint: "19.431275, -99.132424",
  },
  {
    IDENTIFICADOR: "FR06172",
    NOMBRE: "ALAMEDA CENTRAL",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Centro",
    CALLE: "Av. Hidalgo",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 6010,
    CIUDAD: "Ciudad de México",
    ESTATUS: "FALLA ELÉCTRICA - CDMX",
    CONECTIVIDAD: "Sin conexión",
    "APS CONECTADAS": "15/15",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,436179",
    LONGITUD: "-99,144136",
    geopoint: "19.436179, -99.144136",
  },
  {
    IDENTIFICADOR: "FR06085",
    NOMBRE: "PARQUE LORETO Y PEÑA POBRE",
    ALCALDÍA: "TLALPAN",
    COLONIA: "Peña Pobre",
    CALLE: "Av. San Fernando",
    NÚMERO: 765,
    "CÓDIGO POSTAL": 14060,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,296381",
    LONGITUD: "-99,183677",
    geopoint: "19.296381, -99.183677",
  },
  {
    IDENTIFICADOR: "FR06084",
    NOMBRE: "BOSQUE DE TLALPAN",
    ALCALDÍA: "TLALPAN",
    COLONIA: "Parque del Pedregal",
    CALLE: "Camino a Santa Teresa (Entre Zacatépetl y Av. de las Torres)",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 14010,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,291287",
    LONGITUD: "-99,198196",
    geopoint: "19.291287, -99.198196",
  },
  {
    IDENTIFICADOR: "FR03546",
    NOMBRE: "BUNKER AREA DE COMUNICACIÓN (PRENSA)",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Doctores",
    CALLE: "Calle Gral. Gabriel Hernández",
    NÚMERO: 56,
    "CÓDIGO POSTAL": 6720,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,424286",
    LONGITUD: "-99,146773",
    geopoint: "19.424286, -99.146773",
  },
  {
    IDENTIFICADOR: "FR03545",
    NOMBRE: "BUNKER 5o PISO",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Doctores",
    CALLE: "Calle Gral. Gabriel Hernández",
    NÚMERO: 56,
    "CÓDIGO POSTAL": 6720,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,424809",
    LONGITUD: "-99,147031",
    geopoint: "19.424809, -99.147031",
  },
  {
    IDENTIFICADOR: "FR03544",
    NOMBRE: "BUNKER PB",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Doctores",
    CALLE: "Calle Gral. Gabriel Hernández",
    NÚMERO: 56,
    "CÓDIGO POSTAL": 6720,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,423948",
    LONGITUD: "-99,147856",
    geopoint: "19.423948, -99.147856",
  },
  {
    IDENTIFICADOR: "FR03448",
    NOMBRE: "FORO CULTURAL CONTRERAS",
    ALCALDÍA: "MAGDALENA CONTRERAS",
    COLONIA: "La Concepción. Santa María Magdalena Atlitic / Los Dinamos",
    CALLE: "Camino Real de Contreras",
    NÚMERO: 27,
    "CÓDIGO POSTAL": 10830,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,3047303",
    LONGITUD: "-99,2364166",
    geopoint: "19.3047303, -99.2364166",
  },
  {
    IDENTIFICADOR: "FR03447",
    NOMBRE: "EXPLANADA ALCALDÍA MAGDALENA CONTRERAS",
    ALCALDÍA: "TLALPAN",
    COLONIA: "Barranca Seca",
    CALLE: "Av. Álvaro Obregón",
    NÚMERO: 20,
    "CÓDIGO POSTAL": 10580,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "3/3",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,304847",
    LONGITUD: "-99,241511",
    geopoint: "19.304847, -99.241511",
  },
  {
    IDENTIFICADOR: "FR03446",
    NOMBRE: "CASA DE LA CULTURA JESUS REYES HEROLES",
    ALCALDÍA: "COYOACÁN",
    COLONIA: "Barrio de Santa Catarina",
    CALLE: "Avenida Francisco Sosa",
    NÚMERO: 202,
    "CÓDIGO POSTAL": 4010,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Sin conexión",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,349164",
    LONGITUD: "-99,171087",
    geopoint: "19.349164, -99.171087",
  },
  {
    IDENTIFICADOR: "FR03445",
    NOMBRE: "CENTRO DEPORTIVO XOCHIMILCO",
    ALCALDÍA: "XOCHIMILCO",
    COLONIA: "Barrio de San Pedro/Xaltocan",
    CALLE: "Francisco Goitia Esq. 16 de Septiembre",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 16095,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "3/3",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,254956",
    LONGITUD: "-99,107204",
    geopoint: "19.254956, -99.107204",
  },
  {
    IDENTIFICADOR: "FR03444",
    NOMBRE: "EXPLANADA ALCALDÍA XOCHIMILCO",
    ALCALDÍA: "XOCHIMILCO",
    COLONIA: "Barrio El Rosario / Centro Histórico de Xochimilco",
    CALLE: "Guadalupe I. Ramirez",
    NÚMERO: 4,
    "CÓDIGO POSTAL": 16070,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,257382",
    LONGITUD: "-99,109106",
    geopoint: "19.257382, -99.109106",
  },
  {
    IDENTIFICADOR: "FR03442",
    NOMBRE: "FORO CULTURAL COYOACANENCE",
    ALCALDÍA: "COYOACÁN",
    COLONIA: "Villa Coyoacán",
    CALLE: "Calle Allende esquina Avenida Hidalgo",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 4000,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "8/8",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,3503664",
    LONGITUD: "-99,1619375",
    geopoint: "19.3503664, -99.1619375",
  },
  {
    IDENTIFICADOR: "FR03441",
    NOMBRE: "PARQUE ECOLOGICO HUAYAMILPAS",
    ALCALDÍA: "COYOACÁN",
    COLONIA: "Huayamilpas",
    CALLE: "Rey Nezahualcóyotl",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 4390,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,324194",
    LONGITUD: "-99,150474",
    geopoint: "19.324194, -99.150474",
  },
  {
    IDENTIFICADOR: "FR03377",
    NOMBRE: "HOSPITAL PEDIÁTRICO COYOACÁN",
    ALCALDÍA: "COYOACÁN",
    COLONIA: "Del Carmen",
    CALLE: "Moctezuma",
    NÚMERO: 18,
    "CÓDIGO POSTAL": 4000,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,34556",
    LONGITUD: "-99,167877",
    geopoint: "19.34556, -99.167877",
  },
  {
    IDENTIFICADOR: "FR03376",
    NOMBRE: "HOSPITAL PEDIATRICO DE XOCHIMILCO",
    ALCALDÍA: "XOCHIMILCO",
    COLONIA: "Barrio Xaltoca",
    CALLE: "Prolongación 16 de Septiembre, Esq. Calzada Nativitas",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 16090,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,2541281",
    LONGITUD: "-99,1055148",
    geopoint: "19.2541281, -99.1055148",
  },
  {
    IDENTIFICADOR: "FR03375",
    NOMBRE: "TOXICOLOGICO XOCHIMILCO",
    ALCALDÍA: "XOCHIMILCO",
    COLONIA: "Huichapan",
    CALLE: "Av. Prolongación, División del Norte Esq. Av. México",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 16030,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,264846",
    LONGITUD: "-99,114945",
    geopoint: "19.264846, -99.114945",
  },
  {
    IDENTIFICADOR: "FR03374",
    NOMBRE: "HOSPITAL GENERAL XOCO",
    ALCALDÍA: "BENITO JUÁREZ",
    COLONIA: "General Anaya",
    CALLE: "Av. México Coyoacán",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 3340,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,360025",
    LONGITUD: "-99,162389",
    geopoint: "19.360025, -99.162389",
  },
  {
    IDENTIFICADOR: "FR07704",
    NOMBRE: "GLORIETA INSURGENTES",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Roma",
    CALLE: "Cruce entre Avenida Chapultepec y Avenida de los Insurgentes",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 6600,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "8/8",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,4236302",
    LONGITUD: "-99,1652748",
    geopoint: "19.4236302, -99.1652748",
  },
  {
    IDENTIFICADOR: "FR03121",
    NOMBRE: "FARO DE ORIENTE IZTAPALAPA",
    ALCALDÍA: "IZTAPALAPA",
    COLONIA: "Fuentes de Zaragoza",
    CALLE: "Calle Ignacio Zaragoza",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 9150,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,369545",
    LONGITUD: "-99,01004",
    geopoint: "19.369545, -99.01004",
  },
  {
    IDENTIFICADOR: "FR03112",
    NOMBRE: "UNIDAD TOXICOLOGICO VENUSTIANO CARRANZA",
    ALCALDÍA: "VENUSTIANO CARRANZA",
    COLONIA: "Adolfo López Mateos",
    CALLE: "Ernesto P. Uruchurtu Esq. Prolongación Rio Churubusco",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 15790,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,421277",
    LONGITUD: "-99,068987",
    geopoint: "19.421277, -99.068987",
  },
  {
    IDENTIFICADOR: "FR03107",
    NOMBRE: "CLINICA COMUNITARIA SANTA CATARINA",
    ALCALDÍA: "IZTAPALAPA",
    COLONIA: "Miguel de la Madrid",
    CALLE: "Nuevo León",
    NÚMERO: "Mz.38 Lt. 9",
    "CÓDIGO POSTAL": 9698,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,34224",
    LONGITUD: "-99,00276",
    geopoint: "19.34224, -99.00276",
  },
  {
    IDENTIFICADOR: "FR02619",
    NOMBRE: "CASA POPULAR DE LA JUVENTUD",
    ALCALDÍA: "MAGDALENA CONTRERAS",
    COLONIA: "San Jeronimo Ledice",
    CALLE: "Luis Cabrera",
    NÚMERO: 1,
    "CÓDIGO POSTAL": 10200,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,3221582",
    LONGITUD: "-99,2212773",
    geopoint: "19.3221582, -99.2212773",
  },
  {
    IDENTIFICADOR: "FR02617",
    NOMBRE: "PARQUE MEXICO",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Hipódromo Condesa",
    CALLE: "Michoacán esquina Av. México",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 6100,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "19/19",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,411919",
    LONGITUD: "-99,169412",
    geopoint: "19.411919, -99.169412",
  },
  {
    IDENTIFICADOR: "FR02612",
    NOMBRE: "CORREDOR AMSTERDAM",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Hipódromo Condesa",
    CALLE: "Av. Ámsterdam",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 6100,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "11/11",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,410836",
    LONGITUD: "-99,171751",
    geopoint: "19.410836, -99.171751",
  },
  {
    IDENTIFICADOR: "FR02611",
    NOMBRE: "CORREDOR MAZATLAN",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Hipódromo Condesa",
    CALLE: "Av. Mazatlan",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 6140,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,414327",
    LONGITUD: "-99,177195",
    geopoint: "19.414327, -99.177195",
  },
  {
    IDENTIFICADOR: "FR02610",
    NOMBRE: "EXPLANADA TEATRO DE LA JUVENTUD",
    ALCALDÍA: "MIGUEL HIDALGO",
    COLONIA: "Tolteca",
    CALLE: "Calle 10",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 1150,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,390602",
    LONGITUD: "-99,195245",
    geopoint: "19.390602, -99.195245",
  },
  {
    IDENTIFICADOR: "FR02609",
    NOMBRE: "CORREDOR REFORMA (MUSEO RUFINO TAMAYO)",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Bosque de Chapultepec I Secc",
    CALLE: "Av. Paseo de la Reforma",
    NÚMERO: 51,
    "CÓDIGO POSTAL": 11580,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,425725",
    LONGITUD: "-99,1839047",
    geopoint: "19.425725, -99.1839047",
  },
  {
    IDENTIFICADOR: "FR02607",
    NOMBRE: "EXPLANADA DELEGACIONAL ALVARO OBREGON",
    ALCALDÍA: "ÁLVARO OBREGÓN",
    COLONIA: "Tolteca",
    CALLE: "Calle Canario esquina Calle 10",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 1150,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "3/3",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,389437",
    LONGITUD: "-99,195662",
    geopoint: "19.389437, -99.195662",
  },
  {
    IDENTIFICADOR: "FR02606",
    NOMBRE: "PARQUE LIRA",
    ALCALDÍA: "MIGUEL HIDALGO",
    COLONIA: "San Miguel Chapultepec",
    CALLE: "Av. Parque Lira esq. Benjamín Franklin",
    NÚMERO: 136,
    "CÓDIGO POSTAL": 11850,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,406829",
    LONGITUD: "-99,190055",
    geopoint: "19.406829, -99.190055",
  },
  {
    IDENTIFICADOR: "FR02573",
    NOMBRE: "CENTRO COYOACÁN 2° PISO (RECEPCIÓN J)",
    ALCALDÍA: "BENITO JUÁREZ",
    COLONIA: "Xoco",
    CALLE: "Av. Coyoacán",
    NÚMERO: 2000,
    "CÓDIGO POSTAL": 3330,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,366048",
    LONGITUD: "-99,172849",
    geopoint: "19.366048, -99.172849",
  },
  {
    IDENTIFICADOR: "FR02572",
    NOMBRE: "CENTRO COYOACÁN PB (CORREDOR PRINCIPAL)",
    ALCALDÍA: "BENITO JUÁREZ",
    COLONIA: "Xoco",
    CALLE: "Av. Coyoacán",
    NÚMERO: 2000,
    "CÓDIGO POSTAL": 3330,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,366048",
    LONGITUD: "-99,172849",
    geopoint: "19.366048, -99.172849",
  },
  {
    IDENTIFICADOR: "FR02552",
    NOMBRE: "HOSPITAL PEDIÁTRICO TACUBAYA",
    ALCALDÍA: "MIGUEL HIDALGO",
    COLONIA: "Tacubaya",
    CALLE: "Carlos Lazo",
    NÚMERO: 25,
    "CÓDIGO POSTAL": 11870,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,402571",
    LONGITUD: "-99,190816",
    geopoint: "19.402571, -99.190816",
  },
  {
    IDENTIFICADOR: "FR02550",
    NOMBRE: "HOSP. MAT. INF. MAGDALENA CONTRERAS",
    ALCALDÍA: "MAGDALENA CONTRERAS",
    COLONIA: "San Jerónimo Lidice",
    CALLE: "Av. Luis Cabrera",
    NÚMERO: 619,
    "CÓDIGO POSTAL": 10200,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,319737",
    LONGITUD: "-99,239008",
    geopoint: "19.319737, -99.239008",
  },
  {
    IDENTIFICADOR: "FR02549",
    NOMBRE: "HOSPITAL GENERAL ENRIQUE CABRERA",
    ALCALDÍA: "ÁLVARO OBREGÓN",
    COLONIA: "Ex Hacienda de Tarango",
    CALLE: "Av. Centenario esquina prolongación 5 de mayo",
    NÚMERO: 3170,
    "CÓDIGO POSTAL": 1618,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,3608264",
    LONGITUD: "-99,2254211",
    geopoint: "19.3608264, -99.2254211",
  },
  {
    IDENTIFICADOR: "FR02454",
    NOMBRE: "CORREDOR MASARYK",
    ALCALDÍA: "MIGUEL HIDALGO",
    COLONIA: "Polanco",
    CALLE: "Av. Masaryk",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 11550,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "77/77",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,43197",
    LONGITUD: "-99,197941",
    geopoint: "19.43197, -99.197941",
  },
  {
    IDENTIFICADOR: "FR02377",
    NOMBRE: "HOSPITAL PEDIÁTRICO LEGARIA",
    ALCALDÍA: "MIGUEL HIDALGO",
    COLONIA: "México Nuevo",
    CALLE: "Calz. Legaria",
    NÚMERO: 371,
    "CÓDIGO POSTAL": 11260,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,450962",
    LONGITUD: "-99,202658",
    geopoint: "19.450962, -99.202658",
  },
  {
    IDENTIFICADOR: "FR02247",
    NOMBRE: "INSTITUTO DE FORMACIÓN PROFESION AL EDIFICIO ANEXO 40 PISO",
    ALCALDÍA: "AZCAPOTZALCO",
    COLONIA: "Ampliación Cosmopolita",
    CALLE: "Cerrada 4ta. y 5ta. Cerrada de Avenida Jardín",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 2920,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "3/3",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,470476",
    LONGITUD: "-99,160261",
    geopoint: "19.470476, -99.160261",
  },
  {
    IDENTIFICADOR: "FR02246",
    NOMBRE: "INSTITUTO DE FORMACIÓN PROFESIONAL EDIFICIO ANEXO 3ER PISO",
    ALCALDÍA: "AZCAPOTZALCO",
    COLONIA: "Ampliación Cosmopolita",
    CALLE: "Cerrada 4ta. y 5ta. Cerrada de Avenida Jardín",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 2920,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,470476",
    LONGITUD: "-99,160261",
    geopoint: "19.470476, -99.160261",
  },
  {
    IDENTIFICADOR: "FR02245",
    NOMBRE: "INSTITUTO DE FORMACIÓN PROFESIONAL EDIFICIO ANEXO 20 PISO",
    ALCALDÍA: "AZCAPOTZALCO",
    COLONIA: "Ampliación Cosmopolita",
    CALLE: "Cerrada 4ta. y 5ta. Cerrada de Avenida Jardín",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 2920,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,470476",
    LONGITUD: "-99,160497",
    geopoint: "19.470476, -99.160497",
  },
  {
    IDENTIFICADOR: "FR02244",
    NOMBRE: "INSTITUTO DE FORMACIÓN PROFESIONAL EDIFICIO ANEXO PB",
    ALCALDÍA: "AZCAPOTZALCO",
    COLONIA: "Ampliación Cosmopolita",
    CALLE: "Cerrada 4ta. y 5ta. Cerrada de Avenida Jardín",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 2920,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,470476",
    LONGITUD: "-99,160261",
    geopoint: "19.470476, -99.160261",
  },
  {
    IDENTIFICADOR: "FR02181",
    NOMBRE: "HOSPITAL PEDIÁTRICO PERALVILLO",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "San Simón",
    CALLE: "Tolnahuac",
    NÚMERO: 14,
    "CÓDIGO POSTAL": 6920,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,459634",
    LONGITUD: "-99,141319",
    geopoint: "19.459634, -99.141319",
  },
  {
    IDENTIFICADOR: "FR02180",
    NOMBRE: "HOSPITAL PEDIÁTRICO AZCAPOTZALCO",
    ALCALDÍA: "AZCAPOTZALCO",
    COLONIA: "Azcapotzalco",
    CALLE: "Av. Azcapotzalco",
    NÚMERO: 731,
    "CÓDIGO POSTAL": 2000,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,4844906",
    LONGITUD: "-99,1877916",
    geopoint: "19.4844906, -99.1877916",
  },
  {
    IDENTIFICADOR: "FR02176",
    NOMBRE: "CENDI DR. RUBEN LEÑERO",
    ALCALDÍA: "AZCAPOTZALCO",
    COLONIA: "Anáhuac I Secc",
    CALLE: "Colegio Salesiano",
    NÚMERO: 28,
    "CÓDIGO POSTAL": 11320,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "1/1",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,4473176",
    LONGITUD: "-99,1775261",
    geopoint: "19.4473176, -99.1775261",
  },
  {
    IDENTIFICADOR: "FR02175",
    NOMBRE: "HOSPITAL MATERNO INFANTIL CUAUTEPEC",
    ALCALDÍA: "GUSTAVO A. MADERO",
    COLONIA: "Cuautepec de Madero",
    CALLE: "Av. Emiliano Zapata",
    NÚMERO: 700,
    "CÓDIGO POSTAL": 85800,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,5397366",
    LONGITUD: "-99,1425136",
    geopoint: "19.5397366, -99.1425136",
  },
  {
    IDENTIFICADOR: "FR02174",
    NOMBRE: "HOSPITAL GENERAL TICOMÁN",
    ALCALDÍA: "GUSTAVO A. MADERO",
    COLONIA: "La Purísima Ticoman",
    CALLE: "Plan de San Luis",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 7330,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,5131344",
    LONGITUD: "-99,1393567",
    geopoint: "19.5131344, -99.1393567",
  },
  {
    IDENTIFICADOR: "FR02173",
    NOMBRE: "HOSPITAL GENERAL RUBEN LEÑERO",
    ALCALDÍA: "MIGUEL HIDALGO",
    COLONIA: "Santo Tomás",
    CALLE: "Plan de San Luis Esq. Salvador Díaz Mirón",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 11340,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,4513513",
    LONGITUD: "-99,169397",
    geopoint: "19.4513513, -99.169397",
  },
  {
    IDENTIFICADOR: "FR02127",
    NOMBRE: "PLAZA DE LA IGUALDAD",
    ALCALDÍA: "TLÁHUAC",
    COLONIA: "La Asunción, Pueblo de San Juan Ixtayopan",
    CALLE: "Emiliano Zapata",
    NÚMERO: 15,
    "CÓDIGO POSTAL": 13000,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,243268",
    LONGITUD: "-98,995397",
    geopoint: "19.243268, -98.995397",
  },
  {
    IDENTIFICADOR: "FR02125",
    NOMBRE: "FARO MILPA ALTA",
    ALCALDÍA: "MILPA ALTA",
    COLONIA: "San Antonio Tecomitl",
    CALLE: "Dr. Gaston Melo",
    NÚMERO: 40,
    "CÓDIGO POSTAL": 12100,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "3/3",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,221565",
    LONGITUD: "-98,995318",
    geopoint: "19.221565, -98.995318",
  },
  {
    IDENTIFICADOR: "FR02124",
    NOMBRE: "CENTRO CULTURAL FARO TLÁHUAC",
    ALCALDÍA: "TLÁHUAC",
    COLONIA: "Miguel Hidalgo.",
    CALLE: "Av. La Turba int. Bosque de Tláhuac",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 13200,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,287472",
    LONGITUD: "-99,046483",
    geopoint: "19.287472, -99.046483",
  },
  {
    IDENTIFICADOR: "FR02123",
    NOMBRE: "EXPLANADA ALCALDÍA IZTAPALAPA",
    ALCALDÍA: "IZTAPALAPA",
    COLONIA: "Barrio San Lucas",
    CALLE: "Aldama",
    NÚMERO: 63,
    "CÓDIGO POSTAL": 9000,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "5/5",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,359287",
    LONGITUD: "-99,09204",
    geopoint: "19.359287, -99.09204",
  },
  {
    IDENTIFICADOR: "FR02122",
    NOMBRE: "PLAZA PRINCIPAL SAN ANTONIO TECOMITL",
    ALCALDÍA: "MILPA ALTA",
    COLONIA: "Cruztitla (San Antonio Tecómitl)",
    CALLE: "Av. Morelos s/n esquina 5 de mayo",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 12100,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,217479",
    LONGITUD: "-98,993818",
    geopoint: "19.217479, -98.993818",
  },
  {
    IDENTIFICADOR: "FR02121",
    NOMBRE: "EXPLANADA SAN SALVADOR CUAUHTENCO",
    ALCALDÍA: "MILPA ALTA",
    COLONIA: "San Salvador Cuauhtenco",
    CALLE: "Av. Morelos Poniente esq. Jalapa",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 12300,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,192486",
    LONGITUD: "-99,090225",
    geopoint: "19.192486, -99.090225",
  },
  {
    IDENTIFICADOR: "FR02118",
    NOMBRE: "CORREDOR CULTURAL TLÁHUAC",
    ALCALDÍA: "TLÁHUAC",
    COLONIA: "Selene",
    CALLE: "Golfo de los Iris",
    NÚMERO: "",
    "CÓDIGO POSTAL": 13420,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,293429",
    LONGITUD: "-98,998378",
    geopoint: "19.293429, -98.998378",
  },
  {
    IDENTIFICADOR: "FR02117",
    NOMBRE: "EXPLANADA ALCALDÍA MILPA ALTA",
    ALCALDÍA: "MILPA ALTA",
    COLONIA: "Villa Milpa Alta Centro",
    CALLE: "Av. México Esq. Constitución",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 12000,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Sin conexión",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,191952",
    LONGITUD: "-99,023426",
    geopoint: "19.191952, -99.023426",
  },
  {
    IDENTIFICADOR: "FR02115",
    NOMBRE: "JARDÍN EXPLANADA ALCALDÍA TLÁHUAC",
    ALCALDÍA: "TLÁHUAC",
    COLONIA: "La Asunción",
    CALLE: "Av. Tláhuac esquina Nicolás Bravo",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 13000,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,270119",
    LONGITUD: "-99,00507",
    geopoint: "19.270119, -99.00507",
  },
  {
    IDENTIFICADOR: "FR02079",
    NOMBRE: "HOSPITAL PEDIÁTRICO IZTAPALAPA",
    ALCALDÍA: "IZTAPALAPA",
    COLONIA: "Col. Granjas San Antonio.Iztapalapa",
    CALLE: "Av. Ermita Iztapalapa",
    NÚMERO: 780,
    "CÓDIGO POSTAL": 9070,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,356691",
    LONGITUD: "-99,107646",
    geopoint: "19.356691, -99.107646",
  },
  {
    IDENTIFICADOR: "FR02078",
    NOMBRE: "HOSPITAL MEDICO INFANTIL DE TLAHUAC",
    ALCALDÍA: "TLÁHUAC",
    COLONIA: "La Habana",
    CALLE: "Av. Tláhuac Chalco",
    NÚMERO: 231,
    "CÓDIGO POSTAL": 13050,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,265832",
    LONGITUD: "-98,999027",
    geopoint: "19.265832, -98.999027",
  },
  {
    IDENTIFICADOR: "FR02077",
    NOMBRE: "HOSPITAL DE ESPECIALIDADES BELISARIO DOMÍNGUEZ",
    ALCALDÍA: "TLÁHUAC",
    COLONIA: "San Lorenzo Tezonco",
    CALLE: "Av. Tlahuac",
    NÚMERO: 4866,
    "CÓDIGO POSTAL": 9790,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Activo",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,3067206",
    LONGITUD: "-99,0659508",
    geopoint: "19.3067206, -99.0659508",
  },
  {
    IDENTIFICADOR: "FR02074",
    NOMBRE: "HOSPITAL GENERAL MILPA ALTA",
    ALCALDÍA: "MILPA ALTA",
    COLONIA: "Villa Milpa Alta",
    CALLE: "Blv. Nuevo León",
    NÚMERO: 386,
    "CÓDIGO POSTAL": 12000,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,2007661",
    LONGITUD: "-99,0118559",
    geopoint: "19.2007661, -99.0118559",
  },
  {
    IDENTIFICADOR: "FR02073",
    NOMBRE: "HOSPITAL GENERAL IZTAPALAPA",
    ALCALDÍA: "IZTAPALAPA",
    COLONIA: "Citlalli",
    CALLE: "Av. Ermita Iztapalapa",
    NÚMERO: 3018,
    "CÓDIGO POSTAL": 9660,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,343156",
    LONGITUD: "-99,027249",
    geopoint: "19.343156, -99.027249",
  },
  {
    IDENTIFICADOR: "FR01754",
    NOMBRE: "DEPORTIVO LOS GALEANA",
    ALCALDÍA: "GUSTAVO A. MADERO",
    COLONIA: "San Juan de Aragón 7a. Sección",
    CALLE: "José Loreto Fabela",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 7910,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,4782283",
    LONGITUD: "-99,0770988",
    geopoint: "19.4782283, -99.0770988",
  },
  {
    IDENTIFICADOR: "FR01752",
    NOMBRE: "CENTRO REGULADOR DE URGENCIAS",
    ALCALDÍA: "VENUSTIANO CARRANZA",
    COLONIA: "Aeronáutica Militar",
    CALLE: "Estand de Tiro esquina Sur 103",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 15970,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,424181",
    LONGITUD: "-99,116095",
    geopoint: "19.424181, -99.116095",
  },
  {
    IDENTIFICADOR: "FR01751",
    NOMBRE: "ALCALDÍA VENUSTIANO CARRANZA",
    ALCALDÍA: "VENUSTIANO CARRANZA",
    COLONIA: "Jardín Balbuena",
    CALLE: "Eje 3 Ote. (Francisco del Paso y Troncoso)",
    NÚMERO: 219,
    "CÓDIGO POSTAL": 15310,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "6/6",
    "APS SIN CONEXIÓN": "Ninguno",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,419181",
    LONGITUD: "-99,11355",
    geopoint: "19.419181, -99.11355",
  },
  {
    IDENTIFICADOR: "FR01750",
    NOMBRE: "ALCALDÍA IZTACALCO",
    ALCALDÍA: "IZTACALCO",
    COLONIA: "Gabriel Ramos Millán",
    CALLE: "Río Churubusco, esquina Av. Të",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 8000,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,395703",
    LONGITUD: "-99,097152",
    geopoint: "19.395703, -99.097152",
  },
  {
    IDENTIFICADOR: "FR01749",
    NOMBRE: "ALCALDÍA GUSTAVO A MADERO",
    ALCALDÍA: "GUSTAVO A. MADERO",
    COLONIA: "Colonia Villa Gustavo A. Madero",
    CALLE: "5 de Febrero Esq. Vicente Villada",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 7050,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/5",
    "APS SIN CONEXIÓN": 1,
    "GW SIN CONEXIÓN": "GW001",
    LATITUD: "19,4828409",
    LONGITUD: "-99,1144092",
    geopoint: "19.4828409, -99.1144092",
  },
  {
    IDENTIFICADOR: "FR01710",
    NOMBRE: "HOSPITAL PEDIÁTRICO SAN JUAN DE ARAGÓN",
    ALCALDÍA: "GUSTAVO A. MADERO",
    COLONIA: "San Juan de Aragón I Sección",
    CALLE: "Avenida 506",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 7969,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,4571895",
    LONGITUD: "-99,0931355",
    geopoint: "19.4571895, -99.0931355",
  },
  {
    IDENTIFICADOR: "FR01709",
    NOMBRE: "HOSPITAL PEDIÁTRICO MOCTEZUMA",
    ALCALDÍA: "VENUSTIANO CARRANZA",
    COLONIA: "Moctezuma 2Da. Sección",
    CALLE: "Oriente 158",
    NÚMERO: 189,
    "CÓDIGO POSTAL": 15530,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,432626",
    LONGITUD: "-99,098005",
    geopoint: "19.432626, -99.098005",
  },
  {
    IDENTIFICADOR: "FR01708",
    NOMBRE: "HOSPITAL PEDIÁTRICO IZTACALCO",
    ALCALDÍA: "IZTACALCO",
    COLONIA: "La Cruz",
    CALLE: "Av. Coyuya y Terraplén de Rio Frio",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 8310,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,404529",
    LONGITUD: "-99,120145",
    geopoint: "19.404529, -99.120145",
  },
  {
    IDENTIFICADOR: "FR01707",
    NOMBRE: "HOSPITAL MÉDICO INFANTIL INGUARAN",
    ALCALDÍA: "VENUSTIANO CARRANZA",
    COLONIA: "Felipe Ángeles",
    CALLE: "Estaño",
    NÚMERO: 307,
    "CÓDIGO POSTAL": 15530,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,452109",
    LONGITUD: "-99,113003",
    geopoint: "19.452109, -99.113003",
  },
  {
    IDENTIFICADOR: "FR01706",
    NOMBRE: "HOSPITAL GENERAL BALBUENA",
    ALCALDÍA: "VENUSTIANO CARRANZA",
    COLONIA: "Aeronáutica Militar",
    CALLE: "Cecilio Robelo y Sur",
    NÚMERO: 103,
    "CÓDIGO POSTAL": 15970,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,424066",
    LONGITUD: "-99,115283",
    geopoint: "19.424066, -99.115283",
  },
  {
    IDENTIFICADOR: "FR01590",
    NOMBRE: "EXPLANADA ALCALDÍA CUAUHTÉMOC",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Buenavista",
    CALLE: "Aldama y Mina",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 6350,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "3/3",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,4414627",
    LONGITUD: "-99,1523854",
    geopoint: "19.4414627, -99.1523854",
  },
  {
    IDENTIFICADOR: "FR01588",
    NOMBRE: "FARO INDIOS VERDES",
    ALCALDÍA: "GUSTAVO A. MADERO",
    COLONIA: "Santa Isabel Tola",
    CALLE: "Av. Huitzilihuitl",
    NÚMERO: 51,
    "CÓDIGO POSTAL": 7010,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,5036197",
    LONGITUD: "-99,1133648",
    geopoint: "19.5036197, -99.1133648",
  },
  {
    IDENTIFICADOR: "FR01587",
    NOMBRE: "CORREDOR TAMAULIPAS",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Hipódromo Condesa",
    CALLE: "Av. Tamaulipas",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 6170,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,410148",
    LONGITUD: "-99,175074",
    geopoint: "19.410148, -99.175074",
  },
  {
    IDENTIFICADOR: "FR01586",
    NOMBRE: "CORREDOR MICHOACAN",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Hipódromo Condesa",
    CALLE: "Av. Michoacan",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 6140,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "5/5",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,411615",
    LONGITUD: "-99,174042",
    geopoint: "19.411615, -99.174042",
  },
  {
    IDENTIFICADOR: "FR01575",
    NOMBRE: "CORREDOR REFORMA (MUSEO DE ARTE MODERNO)",
    ALCALDÍA: "MIGUEL HIDALGO",
    COLONIA: "Bosque de Chapultepec",
    CALLE: "Paseo de la Reforma y Gandhi",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 11100,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,422278",
    LONGITUD: "-99,179512",
    geopoint: "19.422278, -99.179512",
  },
  {
    IDENTIFICADOR: "FR01574",
    NOMBRE: "EXPLANADA DEL AUDITORIO NACIONAL",
    ALCALDÍA: "MIGUEL HIDALGO",
    COLONIA: "Chapultepec",
    CALLE: "Av. Paseo de la Reforma",
    NÚMERO: 50,
    "CÓDIGO POSTAL": 11580,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,4246889",
    LONGITUD: "-99,1913306",
    geopoint: "19.4246889, -99.1913306",
  },
  {
    IDENTIFICADOR: "FR01562",
    NOMBRE: "KIOSCO MORISCO",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Sta María la Ribera",
    CALLE: "San Salvador Díaz Mirón",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 6400,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,449626",
    LONGITUD: "-99,156746",
    geopoint: "19.449626, -99.156746",
  },
  {
    IDENTIFICADOR: "FR01560",
    NOMBRE: "PARQUE ESPAÑA",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Hipódromo Condesa",
    CALLE: "Parque España",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 6140,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "8/8",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,41526",
    LONGITUD: "-99,172765",
    geopoint: "19.41526, -99.172765",
  },
  {
    IDENTIFICADOR: "FR01554",
    NOMBRE: "CAMPOS ELISEOS",
    ALCALDÍA: "MIGUEL HIDALGO",
    COLONIA: "Polanco 4a Secciión",
    CALLE: "Av. Campos Eliseos",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 11550,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "12/12",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,427819",
    LONGITUD: "-99,193874",
    geopoint: "19.427819, -99.193874",
  },
  {
    IDENTIFICADOR: "FR01405",
    NOMBRE: "INSTITUTO DE FORMACIÓN PROFESIONAL PB",
    ALCALDÍA: "AZCAPOTZALCO",
    COLONIA: "Ampliación Cosmopolita",
    CALLE: "Cerrada 4ta. y 5ta. Cerrada de Avenida Jardín",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 2920,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,470476",
    LONGITUD: "-99,160261",
    geopoint: "19.470476, -99.160261",
  },
  {
    IDENTIFICADOR: "FR01358",
    NOMBRE: "HOSPITAL GENERAL LA VILLA",
    ALCALDÍA: "GUSTAVO A. MADERO",
    COLONIA: "Granjas de San Antonio",
    CALLE: "Av. San Antonio",
    NÚMERO: 285,
    "CÓDIGO POSTAL": 7460,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,4871022",
    LONGITUD: "-99,1142898",
    geopoint: "19.4871022, -99.1142898",
  },
  {
    IDENTIFICADOR: "FR01349",
    NOMBRE: "HOSPITAL MATERNO INFANTIL DR. NICOLÁS M. CEDILLO SORIANO",
    ALCALDÍA: "MIGUEL HIDALGO",
    COLONIA: "Francisco Villa",
    CALLE: "Gustavo J. Esq. Víctor Hernández Covarrubias",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 2400,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "3/3",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,4978824",
    LONGITUD: "-99,2039266",
    geopoint: "19.4978824, -99.2039266",
  },
  {
    IDENTIFICADOR: "FR01348",
    NOMBRE: "HOSPITAL GENERAL GREGORIO SALAS",
    ALCALDÍA: "CUAUHTÉMOC",
    COLONIA: "Centro",
    CALLE: "Carmen",
    NÚMERO: 42,
    "CÓDIGO POSTAL": 6020,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,437722",
    LONGITUD: "-99,129447",
    geopoint: "19.437722, -99.129447",
  },
  {
    IDENTIFICADOR: "FR07741",
    NOMBRE: "EXPLANADA ALCALDÍA MIGUEL HIDALGO",
    ALCALDÍA: "MIGUEL HIDALGO",
    COLONIA: "",
    CALLE: "Parque Lira 94, Ampliacion Daniel Garza, CDMX",
    NÚMERO: 94,
    "CÓDIGO POSTAL": "",
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "3/3",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,41",
    LONGITUD: "-99,19",
    geopoint: "19.41, -99.19",
  },
  {
    IDENTIFICADOR: "FR07742",
    NOMBRE: "EXPLANADA ALCALDÍA BENITO JUAREZ",
    ALCALDÍA: "BENITO JUÁREZ",
    COLONIA: "",
    CALLE: "Av. Divicion del Norte 1611, Sata Cruz Atoyac, CDMX",
    NÚMERO: 1611,
    "CÓDIGO POSTAL": "",
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "3/3",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,37",
    LONGITUD: "-99,16",
    geopoint: "19.37, -99.16",
  },
  {
    IDENTIFICADOR: "FR07739",
    NOMBRE: "EXPLANADA ALCALDÍA AZCAPOTZALCO",
    ALCALDÍA: "AZCAPOTZALCO",
    COLONIA: "",
    CALLE: "Castilla de Oriente s/n, Azcapotzalco Centro, CDMX",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": "",
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "1/1",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,48",
    LONGITUD: "-99,18",
    geopoint: "19.48, -99.18",
  },
  {
    IDENTIFICADOR: "FR07740",
    NOMBRE: "EXPLANADA ALCALDÍA CUAJIMALPA",
    ALCALDÍA: "CUAJIMALPA",
    COLONIA: "",
    CALLE: "Av. Jurez s/n, Cuajimalpa, CDMX",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": "",
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "5/5",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,36",
    LONGITUD: "-99,3",
    geopoint: "19.36, -99.3",
  },
  {
    IDENTIFICADOR: "FR07743",
    NOMBRE: "EXPLANADA ALCALDÍA TLALPAN",
    ALCALDÍA: "TLALPAN",
    COLONIA: "Tlalpan Centro",
    CALLE: "Plaza de la Constitución",
    NÚMERO: 1,
    "CÓDIGO POSTAL": 14000,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "4/4",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,288341",
    LONGITUD: "-99,167126",
    geopoint: "19.288341, -99.167126",
  },
  {
    IDENTIFICADOR: "FR06393",
    NOMBRE: "PARQUE CULTURAL INFANTIL (PATOLLI EL SALADO )",
    ALCALDÍA: "IZTAPALAPA",
    COLONIA: "Solidaridad",
    CALLE: "Alejando Aura",
    NÚMERO: "S/N",
    "CÓDIGO POSTAL": 9510,
    CIUDAD: "Ciudad de México",
    ESTATUS: "VELOCIDAD 200 Mbps",
    CONECTIVIDAD: "Activo",
    "APS CONECTADAS": "2/2",
    "APS SIN CONEXIÓN": "Ninguna",
    "GW SIN CONEXIÓN": "",
    LATITUD: "19,368583",
    LONGITUD: "-99,007662",
    geopoint: "19.368583, -99.007646",
  },
];
